### ISSUE TITLE
Downloading results via script fails

### ISSUE THREAD

**Issue by bricksdont** [hltcoe/turkle#36]
Downloading results for all batches results gives me the following error:

```
$ python download_results.py -u [admin user name] --server [server address]
Admin password:
Traceback (most recent call last):
  File "download_results.py", line 21, in <module>
    result = client.download(args.dir)
  File "/Users/mathiasmuller/Desktop/turkle/scripts/client.py", line 13, in wrapper
    return func(*args, **kwargs)
  File "/Users/mathiasmuller/Desktop/turkle/scripts/client.py", line 70, in download
    for row in soup.find('table', id='result_list').tbody.findAll('tr'):
AttributeError: 'NoneType' object has no attribute 'tbody'
```

Looking at the HTML content in `soup` at

https://github.com/hltcoe/turkle/blob/master/scripts/client.py#L69

it seems the script never makes it past the login page. An excerpt:

```html
<div class="form-row">
<label class="required" for="id_password">Password:</label> <input id="id_password" name="password" required="" type="password"/>
<input name="next" type="hidden" value="/admin/turkle/batch/"/>
</div>
<div class="submit-row">
<label> </label><input type="submit" value="Log in"/>
</div>
</form>
</div>
<br class="clear"/>
</div>
```

I am using current master, and my password is definitely correct.

Thanks so much for your help.

**Comment by cash** [comment]
I've realized that my scripts are hard coded for http and so don't support https. Are you using https?

**Comment by charman** [comment]
The sites I maintain all use https.

**Comment by bricksdont** [comment]
@cash We are using HTTPS.

**Comment by cash** [comment]
I'll get this fixed.

**Comment by bricksdont** [comment]
This also works with current master. Thanks for fixing this! Closing.
