### ISSUE TITLE
Initial step migrate hangs

### ISSUE THREAD

**Issue by bricksdont** [hltcoe/turkle#39]
I'm installing Turkle on a new server, steps:

- virtualenv with Python3, activated it, installed all requirements
- cloned current master from Github

Then, for some reason,

    python manage.py migrate

hangs indefinitely. It also cannot be stopped with Ctrl+C, needs to be killed with SIGKILL. Then I also do not get a traceback.

On my local computer, I did not have this problem; migration went smoothly.

Are there any requirements I am not aware of? Does migrate need write/read permissions in certain places?

**Comment by charman** [comment]
Are you using the default database configuration?  If so, Django should be trying to create a `db.sqlite3` file in the working directory.  What file permissions do you have on the working directory?

**Comment by bricksdont** [comment]
Yes, I did not change anything in the configuration.

Permissions in the working directory:

    drwxr-xr-x 9 mmueller ifi     4096 Jun  6 16:36 turkle

**Comment by charman** [comment]
Try running:

    python manage.py migrate -v 3

(where `-v 3` is maximally verbose logging) and then copy/paste the output here.

**Comment by cash** [comment]
I just changed the permissions to remove write permission and I get a sqlite3.OperationalError: unable to open database file

**Comment by bricksdont** [comment]
I do not get any output,

```
$ time python manage.py migrate -v 3
[killing the process after a few minutes]
zsh: killed     python manage.py migrate -v 3
python manage.py migrate -v 3  0.81s user 0.21s system 0% cpu 2:01.56 total
```

**Comment by cash** [comment]
There should be no dependencies on environment variables or operating system. It's fairly simple as dependencies go.

**Comment by cash** [comment]
Could you run `pip freeze` and post the results here?

**Comment by bricksdont** [comment]
Sure, 
```
$pip freeze
beautifulsoup4==4.7.1
certifi==2019.3.9
chardet==3.0.4
Django==1.11.21
django-dbbackup==3.2.0
django-guardian==1.4.9
django-nose==1.4.5
humanfriendly==4.18
idna==2.8
jsonfield==2.0.2
nose==1.3.7
pytz==2019.1
requests==2.22.0
six==1.12.0
soupsieve==1.9.1
urllib3==1.25.3
```

**Comment by cash** [comment]
I created a venv with those exact dependencies and did not have any problems with the installation. I'm stumped. Now reading through other reports of Django hanging on migrate to some up with ideas...

**Comment by cash** [comment]
Here's an idea: a zombie process that has the database file open. (of course, why did it fail the first time?)

**Comment by bricksdont** [comment]
Oh, after around 20 minutes I got this:

```
python manage.py migrate -v 3
Traceback (most recent call last):
  File "/home/user/mmueller/envs/turkle/lib/python3.5/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/home/user/mmueller/envs/turkle/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 326, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/mmueller/envs/turkle/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/user/mmueller/envs/turkle/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/mmueller/envs/turkle/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/mmueller/envs/turkle/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/user/mmueller/envs/turkle/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/user/mmueller/envs/turkle/lib/python3.5/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/user/mmueller/envs/turkle/lib/python3.5/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/home/user/mmueller/envs/turkle/lib/python3.5/site-packages/django/db/migrations/loader.py", line 210, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/user/mmueller/envs/turkle/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/home/user/mmueller/envs/turkle/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/home/user/mmueller/envs/turkle/lib/python3.5/site-packages/django/db/backends/base/introspection.py", line 55, in table_names
    return get_names(cursor)
  File "/home/user/mmueller/envs/turkle/lib/python3.5/site-packages/django/db/backends/base/introspection.py", line 50, in get_names
    return sorted(ti.name for ti in self.get_table_list(cursor)
  File "/home/user/mmueller/envs/turkle/lib/python3.5/site-packages/django/db/backends/sqlite3/introspection.py", line 69, in get_table_list
    ORDER BY name""")
  File "/home/user/mmueller/envs/turkle/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/user/mmueller/envs/turkle/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/user/mmueller/envs/turkle/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/user/mmueller/envs/turkle/lib/python3.5/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/home/user/mmueller/envs/turkle/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 326, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: database is locked
```

Seems like exactly what you just said, @cash!

- This also happens the first time, and if I delete the DB file
- I do not see such a zombie process.

I will investigate further, perhaps another process on the server is interfering with this. Thanks so much for your help!

**Comment by bricksdont** [comment]
Can I change the location of the DB file by including a path in the settings? Here:

https://github.com/hltcoe/turkle/blob/master/turkle_site/settings.py#L26

**Comment by cash** [comment]
Oh, wow, thanks for figuring this out.

**Comment by bricksdont** [comment]
Closing this now - thanks for the support!
Maybe you could add a note to the section that describes initial DB migrate - but then the problem is very specific.
