### ISSUE TITLE
OverflowError when running migrate on Windows

### ISSUE THREAD

**Issue by ccmaymay** [hltcoe/turkle#43]
When I run `python manage.py migrate` in an anaconda environment with the requirements recently installed on Windows 10, I get this stack trace:

```
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "C:\ProgramData\Anaconda3\envs\coref-annotation\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\ProgramData\Anaconda3\envs\coref-annotation\lib\site-packages\django\core\management\__init__.py", line 338, in execute
    django.setup()
  File "C:\ProgramData\Anaconda3\envs\coref-annotation\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\ProgramData\Anaconda3\envs\coref-annotation\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models()
  File "C:\ProgramData\Anaconda3\envs\coref-annotation\lib\site-packages\django\apps\config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\ProgramData\Anaconda3\envs\coref-annotation\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\cjmay\Documents\turkle\turkle\models.py", line 23, in <module>
    csv.field_size_limit(sys.maxsize)
OverflowError: Python int too large to convert to C long
```

**Comment by cash** [comment]
Fixed by a74620329acaaa962b1442a810fddd1a56221b10
